# paper trading

dev:
  logging_level: DEBUG
  logging_file: "test.log"

ib:
  ip: localhost
  port: 7497
  clientId: 0

alpaca:
  url: https://paper-api.alpaca.markets
  id: "test"
  key: "test"
binance:
  key: "test"
  secret: "test"
aws:
  id: "test"
  key: "test"
bitmex:
  id: "test"
  key: "test"
service:
  airflow:
    email: ["test"]

data:
  base_folder: "goquantdata"
  csv_folder: "raw_data_test"
  bitmex_orderbook:
    s3: "bitmex-orderbook"
    freq: 5
    symbols: ["XBTUSD", "ETHUSD"]

kafka:
  bootstrap_servers: "localhost:9092"
  topic_bitmex_orderbook: "bitmex_orderbook"
